// @ts-nocheck
// This file is autogenerated by scripts/build-examples-index.mts
// Do not edit this file directly.
import * as React from "react"

import examplesData from "./_examplesIndex.json"

type ExampleEntry = {
  name: string
  filePath: string
  component: React.LazyExoticComponent<React.ComponentType<any>>
}

type ExamplesIndexType = Record<string, Record<string, ExampleEntry>>

function createLazyComponent(name: string, folder: string) {
  return React.lazy(async () => {
    const mod = await import(`./${folder}/${name}`)
    const exportName =
      Object.keys(mod).find(
        (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
      ) || name
    return { default: mod.default || mod[exportName] }
  })
}

// Transform the JSON data into the ExamplesIndex format
const buildExamplesIndex = (): ExamplesIndexType => {
  const index: ExamplesIndexType = { base: {} }

  for (const [folder, examples] of Object.entries(examplesData)) {
    for (const example of examples as Array<{ name: string; filePath: string; tags: string[] }>) {
      index.base[example.name] = {
        name: example.name,
        filePath: example.filePath,
        component: createLazyComponent(example.name, folder),
      }
    }
  }

  return index
}

export const ExamplesIndex = buildExamplesIndex()
