// @ts-nocheck
// This file is autogenerated by scripts/build-examples-index.mts
// Do not edit this file directly.
import * as React from "react"

export const ExamplesIndex: Record<string, Record<string, any>> = {
  base: {
    "accordion-basic": {
      name: "accordion-basic",
      filePath: "src/examples/accordion/accordion-basic.tsx",
      component: React.lazy(async () => {
        const mod = await import("./accordion/accordion-basic")
        const exportName =
          Object.keys(mod).find(
            (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || "accordion-basic"
        return { default: mod.default || mod[exportName] }
      }),
    },
    "accordion-borders": {
      name: "accordion-borders",
      filePath: "src/examples/accordion/accordion-borders.tsx",
      component: React.lazy(async () => {
        const mod = await import("./accordion/accordion-borders")
        const exportName =
          Object.keys(mod).find(
            (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || "accordion-borders"
        return { default: mod.default || mod[exportName] }
      }),
    },
    "accordion-card": {
      name: "accordion-card",
      filePath: "src/examples/accordion/accordion-card.tsx",
      component: React.lazy(async () => {
        const mod = await import("./accordion/accordion-card")
        const exportName =
          Object.keys(mod).find(
            (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || "accordion-card"
        return { default: mod.default || mod[exportName] }
      }),
    },
    "accordion-demo": {
      name: "accordion-demo",
      filePath: "src/examples/accordion/accordion-demo.tsx",
      component: React.lazy(async () => {
        const mod = await import("./accordion/accordion-demo")
        const exportName =
          Object.keys(mod).find(
            (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || "accordion-demo"
        return { default: mod.default || mod[exportName] }
      }),
    },
    "accordion-disabled": {
      name: "accordion-disabled",
      filePath: "src/examples/accordion/accordion-disabled.tsx",
      component: React.lazy(async () => {
        const mod = await import("./accordion/accordion-disabled")
        const exportName =
          Object.keys(mod).find(
            (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || "accordion-disabled"
        return { default: mod.default || mod[exportName] }
      }),
    },
    "accordion-multiple": {
      name: "accordion-multiple",
      filePath: "src/examples/accordion/accordion-multiple.tsx",
      component: React.lazy(async () => {
        const mod = await import("./accordion/accordion-multiple")
        const exportName =
          Object.keys(mod).find(
            (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || "accordion-multiple"
        return { default: mod.default || mod[exportName] }
      }),
    },
    "button-default": {
      name: "button-default",
      filePath: "src/examples/button/button-default.tsx",
      component: React.lazy(async () => {
        const mod = await import("./button/button-default")
        const exportName =
          Object.keys(mod).find(
            (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || "button-default"
        return { default: mod.default || mod[exportName] }
      }),
    },
    "button-demo": {
      name: "button-demo",
      filePath: "src/examples/button/button-demo.tsx",
      component: React.lazy(async () => {
        const mod = await import("./button/button-demo")
        const exportName =
          Object.keys(mod).find(
            (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || "button-demo"
        return { default: mod.default || mod[exportName] }
      }),
    },
    "button-destructive": {
      name: "button-destructive",
      filePath: "src/examples/button/button-destructive.tsx",
      component: React.lazy(async () => {
        const mod = await import("./button/button-destructive")
        const exportName =
          Object.keys(mod).find(
            (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || "button-destructive"
        return { default: mod.default || mod[exportName] }
      }),
    },
    "button-ghost": {
      name: "button-ghost",
      filePath: "src/examples/button/button-ghost.tsx",
      component: React.lazy(async () => {
        const mod = await import("./button/button-ghost")
        const exportName =
          Object.keys(mod).find(
            (key) => typeof mod[key] === "function" || typeof mod[key] === "object",
          ) || "button-ghost"
        return { default: mod.default || mod[exportName] }
      }),
    },
  },
}
